name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar ESLint frontend
        run: npm run lint

  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        working-directory: backend
        run: npm ci

      - name: Ejecutar ESLint backend
        working-directory: backend
        run: npm run lint